### ISSUE TITLE
Adapters for Backbone events

### ISSUE THREAD

**Issue by scothis** [cujojs/msgs#11]
http://backbonejs.org/

**Comment by alesco** [comment]
Hi,
what is the road-map? When is planned the release of this features?

**Comment by scothis** [comment]
@alesco The basic idea is to have a msgs.js adapter that can receive Backbone events on a Model/Collection/etc.  The advantage of doing this inside msgs is that we can detach the listener when the bus is destroyed. Once the events are inside the bus, they can be routed, transformed and consumed like any other message which has the effect of decoupling the message source from the message consumer.

If you have other ideas, please share.

I hope to have this complete for 0.4 which should be out in a month or so. It's not a complex bit of code to implement.

**Comment by alesco** [comment]
hi,
I need to do a thorough study before having an opinion. But definitely, I am interested in the subject.
I'll share any ideas...

**Comment by scothis** [comment]
@alesco I took a first pass at adapters for Backbone. Take a look https://github.com/cujojs/msgs/commit/a498ef073f433e45ee1f096131c47cc7d160f7c5

**Comment by scothis** [comment]
on dev
