### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by koppor** [cujojs/msgs#19]
LICENSE.txt has the following paragraph:

```
Code published by Scott Andrews or Mark Fisher is copyright VMware.

VMware, Inc.
3401 Hillview Avenue
Palo Alto, CA 94304
```

This makes the possible use of the library unclear. Following questions:
- Is it possible to remove the contributions of VMware without removing integral parts of the library? Is it possible to rewrite the parts to prevent copyright violation?
- If not, is it possible to license VMware's contributions under MIT?
- If not, is it possible to license VMware's contributions and the whole library under Apache 2.0 license?
- If not, is it possible to license VMwares's contributions under the Eclipse Public License (EPL) and possibly the whole library under EPL?

EPL should not be an issue as VMware published a whole project under EPL: http://eclipse.org/proposals/rt.vertx/

**Comment by scothis** [comment]
@koppor msgs.js is made available, in its entirety, under the MIT license.

As a VMware employee, all of my work product is owned by VMware.  The portion of license.txt you reference is simply trying to acknowledge that VMware holds the copyright for any commit I made.  As the copyright holder, VMware decided to release msgs.js to the community under an MIT license.

Sorry for any confusion.  I'm open to suggestions for making this distinction more clear.

**Comment by koppor** [comment]
Maybe just add " and also licensed under the above license".
